"""Generate sql/02_staging.sql from the real CSV headers.

Every staging column is text and keeps the CSV header name verbatim, so the
DDL cannot drift from the files. Re-run after any change to a processed CSV.
"""
from __future__ import annotations

import csv
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from file_manifest import INPUT_FILES, PROJECT_ROOT, PROCESSED_FACT  # noqa: E402

OUT = PROJECT_ROOT / "sql" / "02_staging.sql"

HEADER = """\
-- =====================================================================
-- Nigeria Business Cost Intelligence - PostgreSQL analytical layer
-- 02. Staging layer: load_audit + 17 staging tables
--
-- GENERATED by src/database/generate_staging_ddl.py - do not hand-edit.
--
-- WHAT THIS LAYER IS. These tables hold the PARSED CSV FIELD VALUES,
-- loaded as text before typed conversion. Column names are the CSV
-- headers; every column is text; nothing is cast, coerced or
-- interpreted here.
--
-- WHAT THIS LAYER IS NOT. It is not a byte-exact copy of the CSV files,
-- and nothing in this design claims that it is. A relational row has no
-- column order guarantee, no quoting, no line terminator and no header,
-- so it cannot reproduce the original bytes.
--
-- WHICH CLAIM IS PROVED BY WHAT:
--   * original input file BYTES      -> SHA-256 in staging.load_audit
--   * parsed FIELD TEXT preservation -> the field-by-field comparison
--                                       run against an independent CSV
--                                       reader after COPY
--   * typed VALUE fidelity           -> the numeric round-trip check
--                                       performed after core is loaded
--
-- Idempotent. Safe to re-run.
-- =====================================================================

SET search_path = staging, public;

-- ---------------------------------------------------------------------
-- Load audit: one row per file per load run, all 17 files
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS staging.load_audit (
    load_id           bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    load_run_id       uuid        NOT NULL,
    source_path       text        NOT NULL,
    target_table      text        NOT NULL,
    file_kind         text        NOT NULL,
    file_sha256       char(64)    NOT NULL,
    file_bytes        bigint      NOT NULL,
    csv_row_count     integer     NOT NULL,
    loaded_row_count  integer     NOT NULL,
    column_count      integer     NOT NULL,
    field_text_match  boolean,
    loaded_at         timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT load_audit_file_kind_ck
        CHECK (file_kind IN ('PROCESSED_FACT','REFERENCE')),
    CONSTRAINT load_audit_sha256_ck
        CHECK (file_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT load_audit_counts_ck
        CHECK (csv_row_count >= 0 AND loaded_row_count >= 0),
    CONSTRAINT load_audit_run_file_uk
        UNIQUE (load_run_id, source_path)
);

COMMENT ON TABLE staging.load_audit IS
  'One row per input file per load run. A run is valid only when all 17 rows '
  'have csv_row_count = loaded_row_count and field_text_match = true.';
COMMENT ON COLUMN staging.load_audit.file_sha256 IS
  'SHA-256 of the file as read. This is what establishes file byte integrity.';
COMMENT ON COLUMN staging.load_audit.field_text_match IS
  'True when every staged field equals the field parsed independently from the CSV.';

CREATE INDEX IF NOT EXISTS load_audit_run_ix ON staging.load_audit (load_run_id);
"""


def sql_ident(name: str) -> str:
    """Quote a CSV header as a PostgreSQL identifier."""
    return '"' + name.replace('"', '""') + '"'


def main() -> int:
    parts = [HEADER]
    total_cols = 0
    for f in INPUT_FILES:
        with f.path.open(encoding="utf-8-sig", newline="") as fh:
            header = next(csv.reader(fh))
        if not header:
            raise SystemExit(f"empty header in {f.source_path}")
        if len(set(header)) != len(header):
            raise SystemExit(f"duplicate column name in {f.source_path}: {header}")
        total_cols += len(header)
        kind = "processed fact" if f.file_kind == PROCESSED_FACT else "reference"
        width = max(len(sql_ident(c)) for c in header)
        cols = ",\n".join(
            f"    {sql_ident(c):<{width}} text" for c in header)
        parts.append(f"""
-- ---------------------------------------------------------------------
-- {f.staging_table}
--   source : {f.source_path}
--   kind   : {kind}
--   rows   : {f.expected_rows:,}   columns: {len(header)}
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS staging.{f.staging_table};
CREATE TABLE staging.{f.staging_table} (
{cols},
    stg_line_number integer NOT NULL,
    stg_load_id     bigint  NOT NULL REFERENCES staging.load_audit(load_id)
);
COMMENT ON TABLE staging.{f.staging_table} IS
  'Parsed CSV field values from {f.source_path} ({f.expected_rows:,} rows), '
  'loaded as text before typed conversion. NOT a byte-exact copy of the file: '
  'file byte integrity is established by the SHA-256 recorded in '
  'staging.load_audit, and these relational rows are not claimed to reproduce '
  'the original CSV bytes.';
""")
    parts.append(f"""
-- =====================================================================
-- {len(INPUT_FILES)} staging tables, {total_cols} source columns in total.
-- =====================================================================
""")
    OUT.write_text("".join(parts), encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(PROJECT_ROOT).as_posix()}: "
          f"{len(INPUT_FILES)} tables, {total_cols} source columns")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
