/// Month grain. Marked as the model's date table.
table dim_date
	dataCategory: Time

	column date
		dataType: dateTime
		isKey
		formatString: yyyy-mm-dd
		sourceColumn: date

	column year
		dataType: int64
		summarizeBy: none
		sourceColumn: year

	column month_number
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: month_number

	column month_label
		dataType: string
		sourceColumn: month_label
		sortByColumn: month_index

	column year_month
		dataType: string
		sourceColumn: year_month

	column month_index
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: month_index

	column in_primary_window
		dataType: boolean
		sourceColumn: in_primary_window

	partition dim_date = m
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\dim_date.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"date", type date}, {"year", Int64.Type}, {"month_number", Int64.Type}, {"month_label", type text}, {"year_month", type text}, {"month_index", Int64.Type}, {"in_primary_window", type logical}}, "en-GB")
				in
				    Typed

