/// The decision messages behind 'What should I pay attention to?'.
table ref_attention

	column rank
		dataType: int64
		summarizeBy: none
		sourceColumn: rank

	column headline
		dataType: string
		sourceColumn: headline

	column detail
		dataType: string
		sourceColumn: detail

	column review
		dataType: string
		sourceColumn: review

	column evidence
		dataType: string
		sourceColumn: evidence

	partition ref_attention = m
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\ref_attention.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"rank", Int64.Type}, {"headline", type text}, {"detail", type text}, {"review", type text}, {"evidence", type text}}, "en-GB")
				in
				    Typed

