/// DISCO GRAIN, single July 2025 cross-section. DELIBERATELY HAS NO RELATIONSHIP to dim_jurisdiction: DisCo territories are not jurisdictions (G4).
table ref_nerc_band

	column service_band
		dataType: string
		sourceColumn: service_band

	column rows
		dataType: int64
		sourceColumn: rows

	column discos
		dataType: int64
		sourceColumn: discos

	column lo
		dataType: double
		sourceColumn: lo

	column median_tariff
		dataType: double
		formatString: #,0.00
		sourceColumn: median_tariff

	column hi
		dataType: double
		sourceColumn: hi

	column spread
		dataType: double
		formatString: #,0.00
		sourceColumn: spread

	partition ref_nerc_band = m
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\ref_nerc_band.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"service_band", type text}, {"rows", Int64.Type}, {"discos", Int64.Type}, {"lo", type number}, {"median_tariff", type number}, {"hi", type number}, {"spread", type number}}, "en-GB")
				in
				    Typed

