-- =====================================================================
-- Nigeria Business Cost Intelligence - PostgreSQL analytical layer
-- 02. Staging layer: load_audit + 17 staging tables
--
-- GENERATED by src/database/generate_staging_ddl.py - do not hand-edit.
--
-- WHAT THIS LAYER IS. These tables hold the PARSED CSV FIELD VALUES,
-- loaded as text before typed conversion. Column names are the CSV
-- headers; every column is text; nothing is cast, coerced or
-- interpreted here.
--
-- WHAT THIS LAYER IS NOT. It is not a byte-exact copy of the CSV files,
-- and nothing in this design claims that it is. A relational row has no
-- column order guarantee, no quoting, no line terminator and no header,
-- so it cannot reproduce the original bytes.
--
-- WHICH CLAIM IS PROVED BY WHAT:
--   * original input file BYTES      -> SHA-256 in staging.load_audit
--   * parsed FIELD TEXT preservation -> the field-by-field comparison
--                                       run against an independent CSV
--                                       reader after COPY
--   * typed VALUE fidelity           -> the numeric round-trip check
--                                       performed after core is loaded
--
-- Idempotent. Safe to re-run.
-- =====================================================================

SET search_path = staging, public;

-- ---------------------------------------------------------------------
-- Load audit: one row per file per load run, all 17 files
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS staging.load_audit (
    load_id           bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    load_run_id       uuid        NOT NULL,
    source_path       text        NOT NULL,
    target_table      text        NOT NULL,
    file_kind         text        NOT NULL,
    file_sha256       char(64)    NOT NULL,
    file_bytes        bigint      NOT NULL,
    csv_row_count     integer     NOT NULL,
    loaded_row_count  integer     NOT NULL,
    column_count      integer     NOT NULL,
    field_text_match  boolean,
    loaded_at         timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT load_audit_file_kind_ck
        CHECK (file_kind IN ('PROCESSED_FACT','REFERENCE')),
    CONSTRAINT load_audit_sha256_ck
        CHECK (file_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT load_audit_counts_ck
        CHECK (csv_row_count >= 0 AND loaded_row_count >= 0),
    CONSTRAINT load_audit_run_file_uk
        UNIQUE (load_run_id, source_path)
);

COMMENT ON TABLE staging.load_audit IS
  'One row per input file per load run. A run is valid only when all 17 rows '
  'have csv_row_count = loaded_row_count and field_text_match = true.';
COMMENT ON COLUMN staging.load_audit.file_sha256 IS
  'SHA-256 of the file as read. This is what establishes file byte integrity.';
COMMENT ON COLUMN staging.load_audit.field_text_match IS
  'True when every staged field equals the field parsed independently from the CSV.';

CREATE INDEX IF NOT EXISTS load_audit_run_ix ON staging.load_audit (load_run_id);

-- ---------------------------------------------------------------------
-- stg_fx_nfem_daily
--   source : data/processed/cbn/fx_nfem_daily.csv
--   kind   : processed fact
--   rows   : 425   columns: 16
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS staging.stg_fx_nfem_daily;
CREATE TABLE staging.stg_fx_nfem_daily (
    "source_id"                   text,
    "observation_date"            text,
    "source_date_label"           text,
    "nfem_rate_ngn_per_usd"       text,
    "highest_rate_ngn_per_usd"    text,
    "lowest_rate_ngn_per_usd"     text,
    "closing_rate_ngn_per_usd"    text,
    "simple_avg_rate_ngn_per_usd" text,
    "interbank_turnover_usd"      text,
    "interbank_deal_count"        text,
    "nfem_turnover_usd"           text,
    "nfem_deal_count"             text,
    "record_status"               text,
    "duplicate_of_source_id"      text,
    "geography_type"              text,
    "source_file"                 text,
    stg_line_number integer NOT NULL,
    stg_load_id     bigint  NOT NULL REFERENCES staging.load_audit(load_id)
);
COMMENT ON TABLE staging.stg_fx_nfem_daily IS
  'Parsed CSV field values from data/processed/cbn/fx_nfem_daily.csv (425 rows), '
  'loaded as text before typed conversion. NOT a byte-exact copy of the file: '
  'file byte integrity is established by the SHA-256 recorded in '
  'staging.load_audit, and these relational rows are not claimed to reproduce '
  'the original CSV bytes.';

-- ---------------------------------------------------------------------
-- stg_petrol_price_monthly
--   source : data/processed/nbs/petrol_price_monthly.csv
--   kind   : processed fact
--   rows   : 2,040   columns: 20
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS staging.stg_petrol_price_monthly;
CREATE TABLE staging.stg_petrol_price_monthly (
    "release_month"         text,
    "observation_month"     text,
    "geography_type"        text,
    "geography_name"        text,
    "geography_raw_label"   text,
    "state"                 text,
    "zone"                  text,
    "is_aggregate"          text,
    "price_ngn_per_litre"   text,
    "unit"                  text,
    "source_period_label"   text,
    "is_primary_release"    text,
    "source_anomaly"        text,
    "header_row_used"       text,
    "source_file"           text,
    "source_member"         text,
    "source_sheet"          text,
    "source_row"            text,
    "source_column_index"   text,
    "source_cell_reference" text,
    stg_line_number integer NOT NULL,
    stg_load_id     bigint  NOT NULL REFERENCES staging.load_audit(load_id)
);
COMMENT ON TABLE staging.stg_petrol_price_monthly IS
  'Parsed CSV field values from data/processed/nbs/petrol_price_monthly.csv (2,040 rows), '
  'loaded as text before typed conversion. NOT a byte-exact copy of the file: '
  'file byte integrity is established by the SHA-256 recorded in '
  'staging.load_audit, and these relational rows are not claimed to reproduce '
  'the original CSV bytes.';

-- ---------------------------------------------------------------------
-- stg_diesel_price_monthly
--   source : data/processed/nbs/diesel_price_monthly.csv
--   kind   : processed fact
--   rows   : 2,244   columns: 20
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS staging.stg_diesel_price_monthly;
CREATE TABLE staging.stg_diesel_price_monthly (
    "release_month"         text,
    "observation_month"     text,
    "geography_type"        text,
    "geography_name"        text,
    "geography_raw_label"   text,
    "state"                 text,
    "zone"                  text,
    "is_aggregate"          text,
    "price_ngn_per_litre"   text,
    "unit"                  text,
    "source_period_label"   text,
    "is_primary_release"    text,
    "source_anomaly"        text,
    "header_row_used"       text,
    "source_file"           text,
    "source_member"         text,
    "source_sheet"          text,
    "source_row"            text,
    "source_column_index"   text,
    "source_cell_reference" text,
    stg_line_number integer NOT NULL,
    stg_load_id     bigint  NOT NULL REFERENCES staging.load_audit(load_id)
);
COMMENT ON TABLE staging.stg_diesel_price_monthly IS
  'Parsed CSV field values from data/processed/nbs/diesel_price_monthly.csv (2,244 rows), '
  'loaded as text before typed conversion. NOT a byte-exact copy of the file: '
  'file byte integrity is established by the SHA-256 recorded in '
  'staging.load_audit, and these relational rows are not claimed to reproduce '
  'the original CSV bytes.';

-- ---------------------------------------------------------------------
-- stg_cooking_gas_price_monthly
--   source : data/processed/nbs/cooking_gas_price_monthly.csv
--   kind   : processed fact
--   rows   : 4,224   columns: 22
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS staging.stg_cooking_gas_price_monthly;
CREATE TABLE staging.stg_cooking_gas_price_monthly (
    "release_month"         text,
    "observation_month"     text,
    "cylinder_size_kg"      text,
    "geography_type"        text,
    "geography_name"        text,
    "geography_raw_label"   text,
    "state"                 text,
    "zone"                  text,
    "is_aggregate"          text,
    "refill_price_ngn"      text,
    "unit"                  text,
    "source_period_label"   text,
    "is_primary_release"    text,
    "source_anomaly"        text,
    "source_banner_text"    text,
    "header_row_used"       text,
    "source_file"           text,
    "source_member"         text,
    "source_sheet"          text,
    "source_row"            text,
    "source_column_index"   text,
    "source_cell_reference" text,
    stg_line_number integer NOT NULL,
    stg_load_id     bigint  NOT NULL REFERENCES staging.load_audit(load_id)
);
COMMENT ON TABLE staging.stg_cooking_gas_price_monthly IS
  'Parsed CSV field values from data/processed/nbs/cooking_gas_price_monthly.csv (4,224 rows), '
  'loaded as text before typed conversion. NOT a byte-exact copy of the file: '
  'file byte integrity is established by the SHA-256 recorded in '
  'staging.load_audit, and these relational rows are not claimed to reproduce '
  'the original CSV bytes.';

-- ---------------------------------------------------------------------
-- stg_cooking_gas_extreme_callout
--   source : data/processed/nbs/cooking_gas_extreme_callout.csv
--   kind   : processed fact
--   rows   : 193   columns: 17
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS staging.stg_cooking_gas_extreme_callout;
CREATE TABLE staging.stg_cooking_gas_extreme_callout (
    "release_month"         text,
    "observation_month"     text,
    "cylinder_size_kg"      text,
    "extreme_type"          text,
    "rank_within_block"     text,
    "state"                 text,
    "zone"                  text,
    "price_ngn"             text,
    "is_shared_extreme"     text,
    "raw_callout_text"      text,
    "tie_member_count"      text,
    "source_file"           text,
    "source_member"         text,
    "source_sheet"          text,
    "source_row"            text,
    "source_column_index"   text,
    "source_cell_reference" text,
    stg_line_number integer NOT NULL,
    stg_load_id     bigint  NOT NULL REFERENCES staging.load_audit(load_id)
);
COMMENT ON TABLE staging.stg_cooking_gas_extreme_callout IS
  'Parsed CSV field values from data/processed/nbs/cooking_gas_extreme_callout.csv (193 rows), '
  'loaded as text before typed conversion. NOT a byte-exact copy of the file: '
  'file byte integrity is established by the SHA-256 recorded in '
  'staging.load_audit, and these relational rows are not claimed to reproduce '
  'the original CSV bytes.';

-- ---------------------------------------------------------------------
-- stg_transport_fare_state_monthly
--   source : data/processed/nbs/transport_fare_state_monthly.csv
--   kind   : processed fact
--   rows   : 3,230   columns: 20
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS staging.stg_transport_fare_state_monthly;
CREATE TABLE staging.stg_transport_fare_state_monthly (
    "observation_month"     text,
    "release_month"         text,
    "transport_mode"        text,
    "transport_mode_raw"    text,
    "geography_type"        text,
    "geography_name"        text,
    "geography_raw_label"   text,
    "state"                 text,
    "zone"                  text,
    "is_aggregate"          text,
    "fare_ngn"              text,
    "unit"                  text,
    "source_period_label"   text,
    "source_anomaly"        text,
    "source_file"           text,
    "source_member"         text,
    "source_sheet"          text,
    "source_row"            text,
    "source_column_index"   text,
    "source_cell_reference" text,
    stg_line_number integer NOT NULL,
    stg_load_id     bigint  NOT NULL REFERENCES staging.load_audit(load_id)
);
COMMENT ON TABLE staging.stg_transport_fare_state_monthly IS
  'Parsed CSV field values from data/processed/nbs/transport_fare_state_monthly.csv (3,230 rows), '
  'loaded as text before typed conversion. NOT a byte-exact copy of the file: '
  'file byte integrity is established by the SHA-256 recorded in '
  'staging.load_audit, and these relational rows are not claimed to reproduce '
  'the original CSV bytes.';

-- ---------------------------------------------------------------------
-- stg_transport_fare_zone_monthly
--   source : data/processed/nbs/transport_fare_zone_monthly.csv
--   kind   : processed fact
--   rows   : 1,785   columns: 21
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS staging.stg_transport_fare_zone_monthly;
CREATE TABLE staging.stg_transport_fare_zone_monthly (
    "release_month"         text,
    "observation_month"     text,
    "transport_mode"        text,
    "transport_mode_raw"    text,
    "geography_type"        text,
    "geography_name"        text,
    "geography_raw_label"   text,
    "zone"                  text,
    "is_aggregate"          text,
    "fare_ngn"              text,
    "unit"                  text,
    "source_period_label"   text,
    "period_position"       text,
    "is_primary_release"    text,
    "source_anomaly"        text,
    "source_file"           text,
    "source_member"         text,
    "source_sheet"          text,
    "source_row"            text,
    "source_column_index"   text,
    "source_cell_reference" text,
    stg_line_number integer NOT NULL,
    stg_load_id     bigint  NOT NULL REFERENCES staging.load_audit(load_id)
);
COMMENT ON TABLE staging.stg_transport_fare_zone_monthly IS
  'Parsed CSV field values from data/processed/nbs/transport_fare_zone_monthly.csv (1,785 rows), '
  'loaded as text before typed conversion. NOT a byte-exact copy of the file: '
  'file byte integrity is established by the SHA-256 recorded in '
  'staging.load_audit, and these relational rows are not claimed to reproduce '
  'the original CSV bytes.';

-- ---------------------------------------------------------------------
-- stg_food_price_national_monthly
--   source : data/processed/nbs/food_price_national_monthly.csv
--   kind   : processed fact
--   rows   : 2,142   columns: 23
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS staging.stg_food_price_national_monthly;
CREATE TABLE staging.stg_food_price_national_monthly (
    "observation_month"     text,
    "release_month"         text,
    "item_code"             text,
    "item_label"            text,
    "item_label_raw"        text,
    "unit"                  text,
    "unit_source"           text,
    "geography_type"        text,
    "geography_name"        text,
    "avg_price_ngn"         text,
    "value_status"          text,
    "period_position"       text,
    "source_period_label"   text,
    "is_primary_release"    text,
    "source_anomaly"        text,
    "header_row_used"       text,
    "header_label_raw"      text,
    "source_file"           text,
    "source_member"         text,
    "source_sheet"          text,
    "source_row"            text,
    "source_column_index"   text,
    "source_cell_reference" text,
    stg_line_number integer NOT NULL,
    stg_load_id     bigint  NOT NULL REFERENCES staging.load_audit(load_id)
);
COMMENT ON TABLE staging.stg_food_price_national_monthly IS
  'Parsed CSV field values from data/processed/nbs/food_price_national_monthly.csv (2,142 rows), '
  'loaded as text before typed conversion. NOT a byte-exact copy of the file: '
  'file byte integrity is established by the SHA-256 recorded in '
  'staging.load_audit, and these relational rows are not claimed to reproduce '
  'the original CSV bytes.';

-- ---------------------------------------------------------------------
-- stg_food_price_zone_monthly
--   source : data/processed/nbs/food_price_zone_monthly.csv
--   kind   : processed fact
--   rows   : 4,284   columns: 21
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS staging.stg_food_price_zone_monthly;
CREATE TABLE staging.stg_food_price_zone_monthly (
    "observation_month"       text,
    "release_month"           text,
    "item_code"               text,
    "item_label"              text,
    "item_label_raw"          text,
    "unit"                    text,
    "unit_source"             text,
    "geography_type"          text,
    "zone"                    text,
    "zone_raw_label"          text,
    "avg_price_ngn"           text,
    "value_status"            text,
    "observation_month_basis" text,
    "source_anomaly"          text,
    "header_row_used"         text,
    "source_file"             text,
    "source_member"           text,
    "source_sheet"            text,
    "source_row"              text,
    "source_column_index"     text,
    "source_cell_reference"   text,
    stg_line_number integer NOT NULL,
    stg_load_id     bigint  NOT NULL REFERENCES staging.load_audit(load_id)
);
COMMENT ON TABLE staging.stg_food_price_zone_monthly IS
  'Parsed CSV field values from data/processed/nbs/food_price_zone_monthly.csv (4,284 rows), '
  'loaded as text before typed conversion. NOT a byte-exact copy of the file: '
  'file byte integrity is established by the SHA-256 recorded in '
  'staging.load_audit, and these relational rows are not claimed to reproduce '
  'the original CSV bytes.';

-- ---------------------------------------------------------------------
-- stg_food_price_extreme_callout
--   source : data/processed/nbs/food_price_extreme_callout.csv
--   kind   : processed fact
--   rows   : 1,428   columns: 24
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS staging.stg_food_price_extreme_callout;
CREATE TABLE staging.stg_food_price_extreme_callout (
    "observation_month"       text,
    "release_month"           text,
    "item_code"               text,
    "item_label"              text,
    "item_label_raw"          text,
    "unit"                    text,
    "unit_source"             text,
    "extreme_type"            text,
    "geography_type"          text,
    "state"                   text,
    "state_raw_label"         text,
    "zone"                    text,
    "price_ngn"               text,
    "is_shared_extreme"       text,
    "raw_callout_text"        text,
    "observation_month_basis" text,
    "source_anomaly"          text,
    "header_row_used"         text,
    "source_file"             text,
    "source_member"           text,
    "source_sheet"            text,
    "source_row"              text,
    "source_column_index"     text,
    "source_cell_reference"   text,
    stg_line_number integer NOT NULL,
    stg_load_id     bigint  NOT NULL REFERENCES staging.load_audit(load_id)
);
COMMENT ON TABLE staging.stg_food_price_extreme_callout IS
  'Parsed CSV field values from data/processed/nbs/food_price_extreme_callout.csv (1,428 rows), '
  'loaded as text before typed conversion. NOT a byte-exact copy of the file: '
  'file byte integrity is established by the SHA-256 recorded in '
  'staging.load_audit, and these relational rows are not claimed to reproduce '
  'the original CSV bytes.';

-- ---------------------------------------------------------------------
-- stg_cpi_state_monthly
--   source : data/processed/nbs/cpi_state_monthly.csv
--   kind   : processed fact
--   rows   : 6,512   columns: 25
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS staging.stg_cpi_state_monthly;
CREATE TABLE staging.stg_cpi_state_monthly (
    "release_month"         text,
    "observation_month"     text,
    "state"                 text,
    "state_raw_label"       text,
    "zone"                  text,
    "geography_type"        text,
    "cpi_group"             text,
    "cpi_group_raw"         text,
    "measure"               text,
    "value"                 text,
    "unit"                  text,
    "base_period"           text,
    "period_position"       text,
    "period_label_raw"      text,
    "is_primary_release"    text,
    "comparability_warning" text,
    "value_status"          text,
    "source_anomaly"        text,
    "extraction_method"     text,
    "source_file"           text,
    "source_member"         text,
    "source_sheet"          text,
    "source_row"            text,
    "source_column_index"   text,
    "source_cell_reference" text,
    stg_line_number integer NOT NULL,
    stg_load_id     bigint  NOT NULL REFERENCES staging.load_audit(load_id)
);
COMMENT ON TABLE staging.stg_cpi_state_monthly IS
  'Parsed CSV field values from data/processed/nbs/cpi_state_monthly.csv (6,512 rows), '
  'loaded as text before typed conversion. NOT a byte-exact copy of the file: '
  'file byte integrity is established by the SHA-256 recorded in '
  'staging.load_audit, and these relational rows are not claimed to reproduce '
  'the original CSV bytes.';

-- ---------------------------------------------------------------------
-- stg_electricity_tariff_disco_period
--   source : data/processed/nerc/electricity_tariff_disco_period.csv
--   kind   : processed fact
--   rows   : 525   columns: 31
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS staging.stg_electricity_tariff_disco_period;
CREATE TABLE staging.stg_electricity_tariff_disco_period (
    "disco_code"               text,
    "disco_official_name"      text,
    "disco_raw_label"          text,
    "tariff_class"             text,
    "tariff_class_raw"         text,
    "service_band"             text,
    "mdclass"                  text,
    "tariff_ngn_per_kwh"       text,
    "unit"                     text,
    "period_start"             text,
    "period_end"               text,
    "period_label_raw"         text,
    "period_position"          text,
    "is_current_period"        text,
    "order_number"             text,
    "order_number_raw"         text,
    "order_effective_date"     text,
    "order_effective_date_raw" text,
    "order_signed_date"        text,
    "signing_date_raw"         text,
    "signing_date_status"      text,
    "website_publication_date" text,
    "vat_treatment"            text,
    "extraction_method"        text,
    "validation_status"        text,
    "source_anomaly"           text,
    "source_file"              text,
    "source_page"              text,
    "source_table_label"       text,
    "source_row_label"         text,
    "source_column_index"      text,
    stg_line_number integer NOT NULL,
    stg_load_id     bigint  NOT NULL REFERENCES staging.load_audit(load_id)
);
COMMENT ON TABLE staging.stg_electricity_tariff_disco_period IS
  'Parsed CSV field values from data/processed/nerc/electricity_tariff_disco_period.csv (525 rows), '
  'loaded as text before typed conversion. NOT a byte-exact copy of the file: '
  'file byte integrity is established by the SHA-256 recorded in '
  'staging.load_audit, and these relational rows are not claimed to reproduce '
  'the original CSV bytes.';

-- ---------------------------------------------------------------------
-- stg_ref_state_zone
--   source : data/reference/ref_state_zone.csv
--   kind   : reference
--   rows   : 39   columns: 7
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS staging.stg_ref_state_zone;
CREATE TABLE staging.stg_ref_state_zone (
    "alias_normalised"    text,
    "state"               text,
    "zone"                text,
    "observed_aliases"    text,
    "alias_variant_count" text,
    "alias_source"        text,
    "observed_in"         text,
    stg_line_number integer NOT NULL,
    stg_load_id     bigint  NOT NULL REFERENCES staging.load_audit(load_id)
);
COMMENT ON TABLE staging.stg_ref_state_zone IS
  'Parsed CSV field values from data/reference/ref_state_zone.csv (39 rows), '
  'loaded as text before typed conversion. NOT a byte-exact copy of the file: '
  'file byte integrity is established by the SHA-256 recorded in '
  'staging.load_audit, and these relational rows are not claimed to reproduce '
  'the original CSV bytes.';

-- ---------------------------------------------------------------------
-- stg_ref_state_alias_observed
--   source : data/reference/ref_state_alias_observed.csv
--   kind   : reference
--   rows   : 77   columns: 6
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS staging.stg_ref_state_alias_observed;
CREATE TABLE staging.stg_ref_state_alias_observed (
    "alias_raw"        text,
    "alias_normalised" text,
    "state"            text,
    "zone"             text,
    "alias_source"     text,
    "observed_in"      text,
    stg_line_number integer NOT NULL,
    stg_load_id     bigint  NOT NULL REFERENCES staging.load_audit(load_id)
);
COMMENT ON TABLE staging.stg_ref_state_alias_observed IS
  'Parsed CSV field values from data/reference/ref_state_alias_observed.csv (77 rows), '
  'loaded as text before typed conversion. NOT a byte-exact copy of the file: '
  'file byte integrity is established by the SHA-256 recorded in '
  'staging.load_audit, and these relational rows are not claimed to reproduce '
  'the original CSV bytes.';

-- ---------------------------------------------------------------------
-- stg_ref_transport_mode
--   source : data/reference/ref_transport_mode.csv
--   kind   : reference
--   rows   : 6   columns: 5
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS staging.stg_ref_transport_mode;
CREATE TABLE staging.stg_ref_transport_mode (
    "transport_mode"   text,
    "raw_label"        text,
    "normalised_label" text,
    "match_prefix"     text,
    "observed_in"      text,
    stg_line_number integer NOT NULL,
    stg_load_id     bigint  NOT NULL REFERENCES staging.load_audit(load_id)
);
COMMENT ON TABLE staging.stg_ref_transport_mode IS
  'Parsed CSV field values from data/reference/ref_transport_mode.csv (6 rows), '
  'loaded as text before typed conversion. NOT a byte-exact copy of the file: '
  'file byte integrity is established by the SHA-256 recorded in '
  'staging.load_audit, and these relational rows are not claimed to reproduce '
  'the original CSV bytes.';

-- ---------------------------------------------------------------------
-- stg_ref_food_item
--   source : data/reference/ref_food_item.csv
--   kind   : reference
--   rows   : 42   columns: 9
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS staging.stg_ref_food_item;
CREATE TABLE staging.stg_ref_food_item (
    "item_code"             text,
    "item_label"            text,
    "item_label_normalised" text,
    "observed_aliases"      text,
    "alias_variant_count"   text,
    "unit"                  text,
    "unit_source"           text,
    "unit_evidence"         text,
    "observed_in"           text,
    stg_line_number integer NOT NULL,
    stg_load_id     bigint  NOT NULL REFERENCES staging.load_audit(load_id)
);
COMMENT ON TABLE staging.stg_ref_food_item IS
  'Parsed CSV field values from data/reference/ref_food_item.csv (42 rows), '
  'loaded as text before typed conversion. NOT a byte-exact copy of the file: '
  'file byte integrity is established by the SHA-256 recorded in '
  'staging.load_audit, and these relational rows are not claimed to reproduce '
  'the original CSV bytes.';

-- ---------------------------------------------------------------------
-- stg_ref_disco
--   source : data/reference/ref_disco.csv
--   kind   : reference
--   rows   : 12   columns: 7
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS staging.stg_ref_disco;
CREATE TABLE staging.stg_ref_disco (
    "disco_code"            text,
    "disco_official_name"   text,
    "observed_aliases"      text,
    "alias_variant_count"   text,
    "alias_normalised_keys" text,
    "state_mapping"         text,
    "notes"                 text,
    stg_line_number integer NOT NULL,
    stg_load_id     bigint  NOT NULL REFERENCES staging.load_audit(load_id)
);
COMMENT ON TABLE staging.stg_ref_disco IS
  'Parsed CSV field values from data/reference/ref_disco.csv (12 rows), '
  'loaded as text before typed conversion. NOT a byte-exact copy of the file: '
  'file byte integrity is established by the SHA-256 recorded in '
  'staging.load_audit, and these relational rows are not claimed to reproduce '
  'the original CSV bytes.';

-- =====================================================================
-- 17 staging tables, 294 source columns in total.
-- =====================================================================
